# Listen on port 80. Match any server name - a catch-all"
server {
    listen $PORT;
    server_name _;

    # Serve files from this folder (where the built React files were copied)
    # Default file to serve is index.html"
    root /usr/share/nginx/html;
    index index.html;

    # For any request, check if the file exists. Check if it's a folder. 
    # Fall back to index.html (React will handle routing)."
    location / {
        try_files $uri $uri/ /index.html;
    }

    # For any request to /api, proxy the request to the backend server (Django)."
    # proxy_set_header lines are used to pass along the original request information to the backend server."
    location /api/ {
        proxy_pass https://flashcards-production-813a.up.railway.app;
        proxy_set_header Host flashcards-production-813a.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass https://flashcards-production-813a.up.railway.app;
        proxy_set_header Host flashcards-production-813a.up.railway.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}



