# Generated by Django 5.2.15 on 2026-07-15 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_deck_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='difficulty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='elapsed_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='lapses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='last_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='scheduled_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='stability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
