# Generated by Django 5.2.15 on 2026-07-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_card_difficulty_card_due_card_elapsed_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='elapsed_days',
            new_name='step',
        ),
        migrations.RemoveField(
            model_name='card',
            name='lapses',
        ),
        migrations.RemoveField(
            model_name='card',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='card',
            name='scheduled_days',
        ),
    ]
