# Generated by Django 5.2.15 on 2026-07-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_elapsed_days_card_step_remove_card_lapses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='difficulty',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='stability',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
